# mode: "batch" # Options: "batch", "window_frame"
mode: "window_frame" # Options: "batch", "window_frame"

default_configs:
  load_full_nodes: &load_full_node false # Options: true, false
  max_steps: &max_steps 200 # Maximum number of steps for the benchmark
  initial_fraction: &initial_fraction 0.4 # Initial fraction of nodes to consider in the benchmark

# Options: "college_msg", "bitcoin_alpha", "bitcoin_otc", "sx-mathoverflow"
target_datasets:
  # - sx-mathoverflow
  - college_msg
  - bitcoin_alpha
  - bitcoin_otc
batch_data_manager:
  college_msg:
    dataset_path: dataset/CollegeMsg.txt
    dataset_type: college_msg
    batch_range: 0.0001
    initial_fraction: *initial_fraction
    max_steps: *max_steps 
    load_full_nodes: *load_full_node
  bitcoin_alpha:
    dataset_path: dataset/soc-sign-bitcoinalpha.csv
    dataset_type: bitcoin_alpha
    batch_range: 0.0001
    initial_fraction: *initial_fraction
    max_steps: *max_steps 
    load_full_nodes: *load_full_node
  bitcoin_otc:
    dataset_path: dataset/soc-sign-bitcoinotc.csv
    dataset_type: bitcoin_otc
    batch_range: 0.001
    initial_fraction: *initial_fraction
    max_steps: *max_steps 
    load_full_nodes: *load_full_node
  sx-mathoverflow:
    dataset_path: dataset/sx-mathoverflow.txt
    dataset_type: sx-mathoverflow
    batch_range: 0.0001
    initial_fraction: *initial_fraction
    max_steps: *max_steps 
    load_full_nodes: *load_full_node
window_frame_data_manager:
  college_msg:
    dataset_path: dataset/CollegeMsg.txt
    dataset_type: college_msg
    window_size: 30
    step_size: 2
    initial_fraction: *initial_fraction
    max_steps: *max_steps 
    load_full_nodes: *load_full_node
  bitcoin_alpha:
    dataset_path: dataset/soc-sign-bitcoinalpha.csv
    dataset_type: bitcoin_alpha
    window_size: 30
    step_size: 2
    initial_fraction: *initial_fraction
    max_steps: *max_steps 
    load_full_nodes: *load_full_node
  bitcoin_otc:
    dataset_path: dataset/soc-sign-bitcoinotc.csv
    dataset_type: bitcoin_otc
    window_size: 30
    step_size: 2
    initial_fraction: *initial_fraction
    max_steps: *max_steps 
    load_full_nodes: *load_full_node
  sx-mathoverflow:
    dataset_path: dataset/sx-mathoverflow.txt
    dataset_type: sx-mathoverflow
    window_size: 30
    step_size: 1
    initial_fraction: *initial_fraction
    max_steps: *max_steps 
    load_full_nodes: *load_full_node
